# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world from the x86 arch!
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get update
    sudo apt install build-essential
    wget https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu/dists/focal/6976a827.gpg.key
    sudo apt-key add 6976a827.gpg.key
    sudo echo 'deb https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu bionic at15.0' >> /etc/apt/sources.list
    sudo apt-get update
    sudo apt-get install advance-toolchain-at15.0-cross-ppc64le
  displayName: 'Install the necessary packages'
