# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- script: echo Hello, world from the x86 arch!
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get update
    sudo apt install build-essential
    wget https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu/dists/bionic/6976a827.gpg.key
    sudo apt-key add 6976a827.gpg.key
    echo "deb https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu bionic at14.0" | sudo tee /etc/apt/sources.list
    sudo apt-get update
    sudo apt-get install advance-toolchain-at14.0-cross-ppc64le
    export PATH=$PATH:/opt/at14.0/bin/
    tee -a demo1.cpp <<EOF
    #include <iostream>
    using namespace std;
    int main()
    {
        cout << "Hello World from C++";
        return 0;
    }
    EOF
    g++ demo1.cpp -o demo1-x86_64
    file demo1-x86_64
    which powerpc64le-linux-gnu-{gcc,ld,objdump,g++}
    powerpc64le-linux-gnu-g++ demo1.cpp -o demo1-ppc64le -static
    file demo1-ppc64le
    ./demo1-ppc64le
    ./demo1-x86_64
  displayName: 'Install the necessary packages'
