# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world from the x86 arch!
  displayName: 'Run a one-line script'

- script: |
    sudo yum install gcc-c++ make
    wget https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/redhat/RHEL8/gpg-pubkey-6976a827-5164221b
    sudo rpm --import gpg-pubkey-6976a827-5164221b
  displayName: 'Install the necessary packages'
